[[worlds]]
name = "outer_wilds"
home = "https://discord.com/channels/731205301247803413/1462820272012005489"
default_url = "https://github.com/Ixrec/OuterWildsArchipelagoRandomizer/releases/download/v{{version}}/outer_wilds.apworld"

[worlds.versions]
"1.2.1" = ""
